                                                             let end=null;
// Generated by CoffeeScript 2.7.0
(function()                                                  {
  var greet, puts, res                                       ;

  ({puts} = require("fxxkinmethod/ruby"))                    ;

  greet = function()                                         {
    return "hi, marron."                                     ;};
  end

  res = greet()                                              ;

  puts(res)                                                  ;}

).call(this)                                                 ;
