                                                            let end=null;
// Generated by CoffeeScript 2.7.0
(function()                                                 {
  var greet, res                                            ;

  greet = function()                                        {
    return "hi, marron."                                    ;};
  end

  res = greet()                                             ;

  console.log(res)                                          ;}

).call(this)                                                ;
